SFEM: blas0.cpp File Reference
blas0.cpp File Reference
#include <cmath>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <iomanip>
#include <iostream>
#include "sfemMath/sfemBlas/blas0.h"
Macros
#define INCX 5
#define INCX 5
#define TIME_SIZE 40
Functions
complex< float > c4_uniform_01 (int &seed)
void c4mat_print (int m, int n, complex< float > a[], string title)
void c4mat_print_some (int m, int n, complex< float > a[], int ilo, int jlo, int ihi, int jhi, string title)
complex< float > * c4mat_test (int n)
complex< float > * c4mat_test_inverse (int n)
complex< float > * c4mat_uniform_01_new (int m, int n, int &seed)
complex< float > * c4vec_uniform_01_new (int n, int &seed)
complex< double > c8_uniform_01 (int &seed)
void c8mat_print (int m, int n, complex< double > a[], string title)
void c8mat_print_some (int m, int n, complex< double > a[], int ilo, int jlo, int ihi, int jhi, string title)
complex< double > * c8mat_test (int n)
complex< double > * c8mat_test_inverse (int n)
complex< double > * c8mat_uniform_01_new (int m, int n, int &seed)
complex< double > * c8vec_uniform_01_new (int n, int &seed)
float cabs1 (complex< float > z)
float cabs2 (complex< float > z)
float cmach (int job)
complex< float > csign1 (complex< float > z1, complex< float > z2)
complex< float > csign2 (complex< float > z1, complex< float > z2)
double dmach (int job)
int i4_max (int i1, int i2)
int i4_min (int i1, int i2)
bool lsame (char ca, char cb)
float r4_abs (float x)
float r4_max (float x, float y)
float r4_sign (float x)
float r4_uniform_01 (int &seed)
float r4_uniform_ab (float a, float b, int &seed)
void r4mat_print (int m, int n, float a[], string title)
void r4mat_print_some (int m, int n, float a[], int ilo, int jlo, int ihi, int jhi, string title)
float * r4mat_test (char trans, int lda, int m, int n)
void r4mat_uniform_01 (int m, int n, int &seed, float r[])
void r4vec_print (int n, float a[], string title)
double r8_abs (double x)
double r8_max (double x, double y)
double r8_sign (double x)
double r8_uniform_01 (int &seed)
double r8_uniform_ab (double a, double b, int &seed)
void r8mat_print (int m, int n, double a[], string title)
void r8mat_print_some (int m, int n, double a[], int ilo, int jlo, int ihi, int jhi, string title)
double * r8mat_test (char trans, int lda, int m, int n)
void r8vec_print (int n, double a[], string title)
void r8mat_uniform_01 (int m, int n, int &seed, double r[])
float smach (int job)
void timestamp ()
int triangle_upper_to_i4 (int i, int j)
void xerbla (string srname, int info)
double zabs1 (complex< double > z)
double zabs2 (complex< double > z)
double zmach (int job)
complex< double > zsign1 (complex< double > z1, complex< double > z2)
complex< double > zsign2 (complex< double > z1, complex< double > z2)
Macro Definition Documentation
INCX [1/2]
#define INCX 5
INCX [2/2]
#define INCX 5
TIME_SIZE
#define TIME_SIZE 40
Function Documentation
c4_uniform_01()
complex<float> c4_uniform_01 (int & seed)
Definition at line 16 of file blas0.cpp.
c4mat_print()
void c4mat_print (int m, int n, complex< float > a[], string title)
Definition at line 86 of file blas0.cpp.
References c4mat_print_some().
c4mat_print_some()
void c4mat_print_some (int m, int n, complex< float > a[], int ilo, int jlo, int ihi, int jhi, string title)
Definition at line 125 of file blas0.cpp.
References i4_max(), and i4_min().
Referenced by c4mat_print().
c4mat_test()
complex<float>* c4mat_test (int n)
Definition at line 230 of file blas0.cpp.
Referenced by c4mat_test_inverse().
c4mat_test_inverse()
complex<float>* c4mat_test_inverse (int n)
Definition at line 279 of file blas0.cpp.
References c4mat_test().
c4mat_uniform_01_new()
complex<float>* c4mat_uniform_01_new (int m, int n, int & seed)
Definition at line 326 of file blas0.cpp.
c4vec_uniform_01_new()
complex<float>* c4vec_uniform_01_new (int n, int & seed)
Definition at line 445 of file blas0.cpp.
c8_uniform_01()
complex<double> c8_uniform_01 (int & seed)
Definition at line 561 of file blas0.cpp.
c8mat_print()
void c8mat_print (int m, int n, complex< double > a[], string title)
Definition at line 630 of file blas0.cpp.
References c8mat_print_some().
c8mat_print_some()
void c8mat_print_some (int m, int n, complex< double > a[], int ilo, int jlo, int ihi, int jhi, string title)
Definition at line 669 of file blas0.cpp.
References i4_max(), and i4_min().
Referenced by c8mat_print().
c8mat_test()
complex<double>* c8mat_test (int n)
Definition at line 774 of file blas0.cpp.
Referenced by c8mat_test_inverse().
c8mat_test_inverse()
complex<double>* c8mat_test_inverse (int n)
Definition at line 823 of file blas0.cpp.
References c8mat_test().
c8mat_uniform_01_new()
complex<double>* c8mat_uniform_01_new (int m, int n, int & seed)
Definition at line 870 of file blas0.cpp.
c8vec_uniform_01_new()
complex<double>* c8vec_uniform_01_new (int n, int & seed)
Definition at line 953 of file blas0.cpp.
cabs1()
float cabs1 (complex< float > z)
Definition at line 1033 of file blas0.cpp.
References r4_abs().
Referenced by csign1().
cabs2()
float cabs2 (complex< float > z)
Definition at line 1090 of file blas0.cpp.
Referenced by csign2().
cmach()
float cmach (int job)
Definition at line 1148 of file blas0.cpp.
csign1()
complex<float> csign1 (complex< float > z1, complex< float > z2)
Definition at line 1294 of file blas0.cpp.
References cabs1().
csign2()
complex<float> csign2 (complex< float > z1, complex< float > z2)
Definition at line 1343 of file blas0.cpp.
References cabs2().
dmach()
double dmach (int job)
Definition at line 1392 of file blas0.cpp.
i4_max()
int i4_max (int i1, int i2)
Definition at line 1516 of file blas0.cpp.
Referenced by c4mat_print_some(), c8mat_print_some(), and r4mat_print_some().
i4_min()
int i4_min (int i1, int i2)
Definition at line 1557 of file blas0.cpp.
Referenced by c4mat_print_some(), c8mat_print_some(), and r4mat_print_some().
lsame()
bool lsame (char ca, char cb)
Definition at line 1598 of file blas0.cpp.
r4_abs()
float r4_abs (float x)
Definition at line 1664 of file blas0.cpp.
Referenced by cabs1().
r4_max()
float r4_max (float x, float y)
Definition at line 1705 of file blas0.cpp.
r4_sign()
float r4_sign (float x)
Definition at line 1746 of file blas0.cpp.
r4_uniform_01()
float r4_uniform_01 (int & seed)
Definition at line 1787 of file blas0.cpp.
r4_uniform_ab()
float r4_uniform_ab (float a, float b, int & seed)
Definition at line 1888 of file blas0.cpp.
r4mat_print()
void r4mat_print (int m, int n, float a[], string title)
Definition at line 1952 of file blas0.cpp.
References r4mat_print_some().
r4mat_print_some()
void r4mat_print_some (int m, int n, float a[], int ilo, int jlo, int ihi, int jhi, string title)
Definition at line 1996 of file blas0.cpp.
References i4_max(), i4_min(), and INCX.
Referenced by r4mat_print().
r4mat_test()
float* r4mat_test (char trans, int lda, int m, int n)
Definition at line 2104 of file blas0.cpp.
r4mat_uniform_01()
void r4mat_uniform_01 (int m, int n, int & seed, float r[])
Definition at line 2173 of file blas0.cpp.
r4vec_print()
void r4vec_print (int n, float a[], string title)
Definition at line 2278 of file blas0.cpp.
r8_abs()
double r8_abs (double x)
Definition at line 2326 of file blas0.cpp.
r8_max()
double r8_max (double x, double y)
Definition at line 2367 of file blas0.cpp.
r8_sign()
double r8_sign (double x)
Definition at line 2408 of file blas0.cpp.
Referenced by drotg().
r8_uniform_01()
double r8_uniform_01 (int & seed)
Definition at line 2449 of file blas0.cpp.
r8_uniform_ab()
double r8_uniform_ab (double a, double b, int & seed)
Definition at line 2552 of file blas0.cpp.
r8mat_print()
void r8mat_print (int m, int n, double a[], string title)
Definition at line 2616 of file blas0.cpp.
References r8mat_print_some().
r8mat_print_some()
void r8mat_print_some (int m, int n, double a[], int ilo, int jlo, int ihi, int jhi, string title)
Definition at line 2660 of file blas0.cpp.
References INCX.
Referenced by r8mat_print().
r8mat_test()
double* r8mat_test (char trans, int lda, int m, int n)
Definition at line 2787 of file blas0.cpp.
r8mat_uniform_01()
void r8mat_uniform_01 (int m, int n, int & seed, double r[])
Definition at line 2904 of file blas0.cpp.
r8vec_print()
void r8vec_print (int n, double a[], string title)
Definition at line 2856 of file blas0.cpp.
smach()
float smach (int job)
Definition at line 3009 of file blas0.cpp.
References xerbla().
timestamp()
void timestamp ()
Definition at line 3128 of file blas0.cpp.
References TIME_SIZE.
triangle_upper_to_i4()
int triangle_upper_to_i4 (int i, int j)
Definition at line 3175 of file blas0.cpp.
xerbla()
void xerbla (string srname, int info)
Definition at line 3283 of file blas0.cpp.
Referenced by smach().
zabs1()
double zabs1 (complex< double > z)
Definition at line 3335 of file blas0.cpp.
Referenced by zsign1().
zabs2()
double zabs2 (complex< double > z)
Definition at line 3390 of file blas0.cpp.
Referenced by zsign2().
zmach()
double zmach (int job)
Definition at line 3449 of file blas0.cpp.
zsign1()
complex<double> zsign1 (complex< double > z1, complex< double > z2)
Definition at line 3593 of file blas0.cpp.
References zabs1().
zsign2()
complex<double> zsign2 (complex< double > z1, complex< double > z2)
Definition at line 3642 of file blas0.cpp.
References zabs2().
This page is part of the SFEM-1.0 documentation. Copyright Copyright (C) 2021 Qiang Sun
Project e-mail: sunqiang891103@gmail.com
Generated at Sun Dec 12 2021 14:51:04 for SFEM by doxygen 1.8.17 written by Dimitri van Heesch, © 2021